### ISSUE TITLE
Add absolute path when import

### ISSUE THREAD

**Issue by BrunoBNascimento** [bowe-td/react-web-example#5]
Example:
```js
import { Component } from 'components'
```

Instead of

```js
import { Component } from '../components'
```

@heitortv @vinilopes91 @MattCarval

**Comment by heitortv** [comment]
`import Thing from 'components/Thing`;
or
`import Thing from '@/components/Thing'`;
or
`import Thing from 'src/components/Thing'`;
or another style?

**Comment by BrunoBNascimento** [comment]
import Thing from '@/components/Thing' BEST way

**Comment by heitortv** [comment]
did in the first style `import Thing from 'components/Thing;` as recommended on the CRA docs
